#!/usr/bin/env bash

source ../.defaults

OUTFILE=minishell.out
CMPFILE=.infile.diff

# Unquote EOF if bash variable interpolation is required
$BINARY > $OUTFILE 2> /dev/null .infile.sh

MSH_RET=$?

diff -u $CMPFILE $OUTFILE

RET=$?

# Cleanup testing files
rm $OUTFILE

# Check shell return code
if [ $MSH_RET != 117 ]
then
    exit 1
fi

# Else check diff return code
exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
