#!/usr/bin/env bash

source ../.defaults

OUTFILE=minishell.out
ERRFILE=err.txt

$BINARY > $OUTFILE 2> $ERRFILE <<EOF
echo "Stuff happens here"
echo harder" stuff and things"
echo "other stuff and things"  
echo " things that might not seem "hard
echo " and legitimately"hard seeming stuff   
EOF

MSH_RET=$?

diff -u .quotes.diff $OUTFILE

RET=$?

echo "Error output:"
cat $ERRFILE

# Cleanup testing files
rm $OUTFILE $ERRFILE

if [ $MSH_RET != 0 ]
then
    exit 1
fi

exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
