#!/usr/bin/env bash

source ../.defaults

$BINARY > minishell.out <<EOF
echo "Stuff happens here"
echo harder" stuff and things"
echo "other stuff and things"  
echo " things that might not seem "hard
echo " and legitimately"hard seeming stuff   
EOF

diff -u minishell.out .quotes.diff

RET=$?

rm minishell.out

exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
