#!/usr/bin/env bash

source ../.defaults

$BINARY > minishell.out <<EOF
echo
echo Hello
 echo Hi
echo How are you?  
echo    I'm just fine
      echo   and   I don't     care about     spaces!!!!   
EOF

MSH_RET=$?

diff -u minishell.out .spaces.diff

RET=$?

rm minishell.out

if [ $MSH_RET != 0 ]
then
    exit 1
fi

exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
