#!/usr/bin/env bash

source ../.defaults

OUTFILE=minishell.out
ERRFILE=err.txt

$BINARY > $OUTFILE 2> $ERRFILE <<EOF
echo
echo Hello
 echo Hi
echo How are you?  
echo    I'm just fine
      echo   and   I don't     care about     spaces!!!!   
EOF

MSH_RET=$?

diff -u .spaces.diff minishell.out

RET=$?

echo "Error output:"
cat $ERRFILE

rm $OUTFILE $ERRFILE

if [ $MSH_RET != 0 ]
then
    exit 1
fi

exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
