#!/usr/bin/env bash

source ../.defaults

OUTFILE=minishell.out
ERRFILE=err.txt

$BINARY > $OUTFILE 2> $ERRFILE <<EOF
aecho
aecho -n "thing"
aecho stuff
aecho -n
aecho a b c d e
aecho -n a"  "b c d
aecho last
EOF

MSH_RET=$?

diff -u .aecho.diff minishell.out

RET=$?

echo "Error output:"
cat $ERRFILE

rm $OUTFILE $ERRFILE

if [ $MSH_RET != 0 ]
then
    exit 1
fi

exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
