#!/usr/bin/env bash

source ../.defaults

OUTFILE=minishell.out
ERRFILE=err.txt
CMPFILE=cd.diff

$BINARY > $OUTFILE 2> $ERRFILE <<EOF
    pwd
    cd ../
    pwd
    cd
    pwd
EOF

MSH_RET=$?

(
    pwd
    cd ../
    pwd
    cd
    pwd
) > $CMPFILE

diff -u cd.diff $OUTFILE

RET=$?

echo "Error output:"
cat $ERRFILE

# Cleanup testing files
rm $OUTFILE $CMPFILE $ERRFILE

# Check shell return code
if [ $MSH_RET != 0 ]
then
    exit 1
fi

# Else check diff return code
exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
