#!/usr/bin/env bash

source ../.defaults

OUTFILE=minishell.out
CMPFILE=pid.diff

# How do I actually test the $$ command?
$BINARY > $OUTFILE 2> /dev/null < .pid-commands &

PID=$!
echo $PID > $CMPFILE

wait $PID
MSH_RET=$?

diff -u $CMPFILE $OUTFILE

RET=$?

# Cleanup testing files
rm $OUTFILE $CMPFILE

# Check shell return code
if [ $MSH_RET != 0 ]
then
    exit 1
fi

# Else check diff return code
exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
