#!/usr/bin/env bash

source ../.defaults

OUTFILE=minishell.out
CMPFILE=.test.diff
ERRFILE=err.txt

# Unquote EOF if bash variable interpolation is required
$BINARY > $OUTFILE 2> $ERRFILE <<'EOF'
echo $0
EOF

MSH_RET=$?

echo > $CMPFILE $BINARY

diff -u $CMPFILE $OUTFILE

RET=$?

echo "Error output:"
cat $ERRFILE

# Cleanup testing files
rm $OUTFILE $CMPFILE $ERRFILE

# Check shell return code
if [ $MSH_RET != 0 ]
then
    echo "Minishell exited with code $MSH_RET"
    exit 1
fi

# Else check diff return code
exit $RET

# Local Variables:
# mode: shell-script
# prelude-clean-whitespace-on-save: nil
# End:
